package whatsapp

import (
	"time"
)

// Default send message response
// Returns unique id generated by service
// Returns timestamp that the server received the message
type IWhatsappSendResponse interface {
	// Returns Message unique id auto-generated
	GetId() string

	// Get the time of server processed message
	GetTime() time.Time

	// Get the time on unix timestamp format
	GetTimestamp() uint64
}
