package whatsapp

import (
	"time"
)

// Default send message response
// Returns unique id generated by service
// Returns timestamp that the server received the message
type WhatsappSendResponse struct {
	// Unique ID Auto-Generated
	ID string

	// Time that server processed the message
	Timestamp time.Time
}

func (source *WhatsappSendResponse) GetId() string {
	return source.ID
}

func (source *WhatsappSendResponse) GetTime() time.Time {
	return source.Timestamp
}

func (source *WhatsappSendResponse) GetTimestamp() uint64 {
	return uint64(source.Timestamp.Unix())
}
