// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: tables.proto

package tables

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The embedded MLow heap window: the runtime-built table regions plus the
// table-base pointers. Stored zlib-compressed.
type HeapWindow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regions       []*Region              `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	GCc           uint32                 `protobuf:"varint,2,opt,name=g_cc,json=gCc,proto3" json:"g_cc,omitempty"`
	GNrg          uint32                 `protobuf:"varint,3,opt,name=g_nrg,json=gNrg,proto3" json:"g_nrg,omitempty"`
	GPitch        uint32                 `protobuf:"varint,4,opt,name=g_pitch,json=gPitch,proto3" json:"g_pitch,omitempty"`
	GClk          uint32                 `protobuf:"varint,5,opt,name=g_clk,json=gClk,proto3" json:"g_clk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeapWindow) Reset() {
	*x = HeapWindow{}
	mi := &file_tables_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeapWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeapWindow) ProtoMessage() {}

func (x *HeapWindow) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeapWindow.ProtoReflect.Descriptor instead.
func (*HeapWindow) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{0}
}

func (x *HeapWindow) GetRegions() []*Region {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *HeapWindow) GetGCc() uint32 {
	if x != nil {
		return x.GCc
	}
	return 0
}

func (x *HeapWindow) GetGNrg() uint32 {
	if x != nil {
		return x.GNrg
	}
	return 0
}

func (x *HeapWindow) GetGPitch() uint32 {
	if x != nil {
		return x.GPitch
	}
	return 0
}

func (x *HeapWindow) GetGClk() uint32 {
	if x != nil {
		return x.GClk
	}
	return 0
}

// One contiguous heap region: its absolute base address and bytes.
type Region struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          uint32                 `protobuf:"varint,1,opt,name=base,proto3" json:"base,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_tables_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{1}
}

func (x *Region) GetBase() uint32 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *Region) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// The MLow per-frame LSF runtime CDF tables (func 3559 output, the lsf_* fields
// of the smpl_tables JSON dump). Stored zlib-compressed protobuf so the Rust
// reference and the Go port decode the byte-identical blob. u16 CDF entries are
// widened to uint32 on the wire (protobuf has no u16) and narrowed back on load.
type SmplLsfTables struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LsfSel        []*Cdf                 `protobuf:"bytes,1,rep,name=lsf_sel,json=lsfSel,proto3" json:"lsf_sel,omitempty"` // [sel] -> CDF
	LsfGrid       *LsfGrid               `protobuf:"bytes,2,opt,name=lsf_grid,json=lsfGrid,proto3" json:"lsf_grid,omitempty"`
	LsfStage2     []*LsfStage2S1         `protobuf:"bytes,3,rep,name=lsf_stage2,json=lsfStage2,proto3" json:"lsf_stage2,omitempty"`      // [stage1]
	LsfExtra      []uint32               `protobuf:"varint,4,rep,packed,name=lsf_extra,json=lsfExtra,proto3" json:"lsf_extra,omitempty"` // the 3-symbol extra CDF
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmplLsfTables) Reset() {
	*x = SmplLsfTables{}
	mi := &file_tables_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmplLsfTables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmplLsfTables) ProtoMessage() {}

func (x *SmplLsfTables) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmplLsfTables.ProtoReflect.Descriptor instead.
func (*SmplLsfTables) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{2}
}

func (x *SmplLsfTables) GetLsfSel() []*Cdf {
	if x != nil {
		return x.LsfSel
	}
	return nil
}

func (x *SmplLsfTables) GetLsfGrid() *LsfGrid {
	if x != nil {
		return x.LsfGrid
	}
	return nil
}

func (x *SmplLsfTables) GetLsfStage2() []*LsfStage2S1 {
	if x != nil {
		return x.LsfStage2
	}
	return nil
}

func (x *SmplLsfTables) GetLsfExtra() []uint32 {
	if x != nil {
		return x.LsfExtra
	}
	return nil
}

// One u16 cumulative CDF.
type Cdf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             []uint32               `protobuf:"varint,1,rep,packed,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cdf) Reset() {
	*x = Cdf{}
	mi := &file_tables_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cdf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cdf) ProtoMessage() {}

func (x *Cdf) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cdf.ProtoReflect.Descriptor instead.
func (*Cdf) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{3}
}

func (x *Cdf) GetV() []uint32 {
	if x != nil {
		return x.V
	}
	return nil
}

// The four stage-1 grid CDFs, selected by (match, stage1 != 0).
type LsfGrid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match1        []uint32               `protobuf:"varint,1,rep,packed,name=match1,proto3" json:"match1,omitempty"`
	Match1Alt     []uint32               `protobuf:"varint,2,rep,packed,name=match1_alt,json=match1Alt,proto3" json:"match1_alt,omitempty"`
	Match0        []uint32               `protobuf:"varint,3,rep,packed,name=match0,proto3" json:"match0,omitempty"`
	Match0Alt     []uint32               `protobuf:"varint,4,rep,packed,name=match0_alt,json=match0Alt,proto3" json:"match0_alt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsfGrid) Reset() {
	*x = LsfGrid{}
	mi := &file_tables_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsfGrid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsfGrid) ProtoMessage() {}

func (x *LsfGrid) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsfGrid.ProtoReflect.Descriptor instead.
func (*LsfGrid) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{4}
}

func (x *LsfGrid) GetMatch1() []uint32 {
	if x != nil {
		return x.Match1
	}
	return nil
}

func (x *LsfGrid) GetMatch1Alt() []uint32 {
	if x != nil {
		return x.Match1Alt
	}
	return nil
}

func (x *LsfGrid) GetMatch0() []uint32 {
	if x != nil {
		return x.Match0
	}
	return nil
}

func (x *LsfGrid) GetMatch0Alt() []uint32 {
	if x != nil {
		return x.Match0Alt
	}
	return nil
}

// lsf_stage2 nesting: [stage1][config][grid][coeff] -> CDF.
type LsfStage2S1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []*LsfStage2S2         `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsfStage2S1) Reset() {
	*x = LsfStage2S1{}
	mi := &file_tables_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsfStage2S1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsfStage2S1) ProtoMessage() {}

func (x *LsfStage2S1) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsfStage2S1.ProtoReflect.Descriptor instead.
func (*LsfStage2S1) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{5}
}

func (x *LsfStage2S1) GetConfig() []*LsfStage2S2 {
	if x != nil {
		return x.Config
	}
	return nil
}

type LsfStage2S2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grid          []*LsfStage2S3         `protobuf:"bytes,1,rep,name=grid,proto3" json:"grid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsfStage2S2) Reset() {
	*x = LsfStage2S2{}
	mi := &file_tables_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsfStage2S2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsfStage2S2) ProtoMessage() {}

func (x *LsfStage2S2) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsfStage2S2.ProtoReflect.Descriptor instead.
func (*LsfStage2S2) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{6}
}

func (x *LsfStage2S2) GetGrid() []*LsfStage2S3 {
	if x != nil {
		return x.Grid
	}
	return nil
}

type LsfStage2S3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coeff         []*Cdf                 `protobuf:"bytes,1,rep,name=coeff,proto3" json:"coeff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsfStage2S3) Reset() {
	*x = LsfStage2S3{}
	mi := &file_tables_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsfStage2S3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsfStage2S3) ProtoMessage() {}

func (x *LsfStage2S3) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsfStage2S3.ProtoReflect.Descriptor instead.
func (*LsfStage2S3) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{7}
}

func (x *LsfStage2S3) GetCoeff() []*Cdf {
	if x != nil {
		return x.Coeff
	}
	return nil
}

// Generic nested-float wrappers (protobuf has no nested repeated): F<N> is a
// depth-N `[[...float]]`. Shared with the reference tables.proto.
type F1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             []float32              `protobuf:"fixed32,1,rep,packed,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *F1) Reset() {
	*x = F1{}
	mi := &file_tables_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *F1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*F1) ProtoMessage() {}

func (x *F1) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use F1.ProtoReflect.Descriptor instead.
func (*F1) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{8}
}

func (x *F1) GetV() []float32 {
	if x != nil {
		return x.V
	}
	return nil
}

type F2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D             []*F1                  `protobuf:"bytes,1,rep,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *F2) Reset() {
	*x = F2{}
	mi := &file_tables_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *F2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*F2) ProtoMessage() {}

func (x *F2) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use F2.ProtoReflect.Descriptor instead.
func (*F2) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{9}
}

func (x *F2) GetD() []*F1 {
	if x != nil {
		return x.D
	}
	return nil
}

type F3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D             []*F2                  `protobuf:"bytes,1,rep,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *F3) Reset() {
	*x = F3{}
	mi := &file_tables_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *F3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*F3) ProtoMessage() {}

func (x *F3) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use F3.ProtoReflect.Descriptor instead.
func (*F3) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{10}
}

func (x *F3) GetD() []*F2 {
	if x != nil {
		return x.D
	}
	return nil
}

type F4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D             []*F3                  `protobuf:"bytes,1,rep,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *F4) Reset() {
	*x = F4{}
	mi := &file_tables_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *F4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*F4) ProtoMessage() {}

func (x *F4) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use F4.ProtoReflect.Descriptor instead.
func (*F4) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{11}
}

func (x *F4) GetD() []*F3 {
	if x != nil {
		return x.D
	}
	return nil
}

type F5 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D             []*F4                  `protobuf:"bytes,1,rep,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *F5) Reset() {
	*x = F5{}
	mi := &file_tables_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *F5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*F5) ProtoMessage() {}

func (x *F5) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use F5.ProtoReflect.Descriptor instead.
func (*F5) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{12}
}

func (x *F5) GetD() []*F4 {
	if x != nil {
		return x.D
	}
	return nil
}

// Generic uint32 / int32 nests (index & CMF tables: pitch, lsf_cb).
type U1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             []uint32               `protobuf:"varint,1,rep,packed,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *U1) Reset() {
	*x = U1{}
	mi := &file_tables_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *U1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*U1) ProtoMessage() {}

func (x *U1) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use U1.ProtoReflect.Descriptor instead.
func (*U1) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{13}
}

func (x *U1) GetV() []uint32 {
	if x != nil {
		return x.V
	}
	return nil
}

type I1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             []int32                `protobuf:"varint,1,rep,packed,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I1) Reset() {
	*x = I1{}
	mi := &file_tables_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I1) ProtoMessage() {}

func (x *I1) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I1.ProtoReflect.Descriptor instead.
func (*I1) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{14}
}

func (x *I1) GetV() []int32 {
	if x != nil {
		return x.V
	}
	return nil
}

type I2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D             []*I1                  `protobuf:"bytes,1,rep,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I2) Reset() {
	*x = I2{}
	mi := &file_tables_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I2) ProtoMessage() {}

func (x *I2) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I2.ProtoReflect.Descriptor instead.
func (*I2) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{15}
}

func (x *I2) GetD() []*I1 {
	if x != nil {
		return x.D
	}
	return nil
}

type I3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D             []*I2                  `protobuf:"bytes,1,rep,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I3) Reset() {
	*x = I3{}
	mi := &file_tables_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I3) ProtoMessage() {}

func (x *I3) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I3.ProtoReflect.Descriptor instead.
func (*I3) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{16}
}

func (x *I3) GetD() []*I2 {
	if x != nil {
		return x.D
	}
	return nil
}

type I4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D             []*I3                  `protobuf:"bytes,1,rep,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I4) Reset() {
	*x = I4{}
	mi := &file_tables_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I4) ProtoMessage() {}

func (x *I4) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I4.ProtoReflect.Descriptor instead.
func (*I4) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{17}
}

func (x *I4) GetD() []*I3 {
	if x != nil {
		return x.D
	}
	return nil
}

// MLow synthesis tables (the runtime smpl_synth_tables dump). Stored zlib+protobuf.
type SmplSynthTables struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Valtables      *F5                    `protobuf:"bytes,1,opt,name=valtables,proto3" json:"valtables,omitempty"`                     // [stage1][config][grid][coeff] -> residual values
	Centroids      *F3                    `protobuf:"bytes,2,opt,name=centroids,proto3" json:"centroids,omitempty"`                     // [stage1][grid] -> 16 base NLSF
	Matrices       *F4                    `protobuf:"bytes,3,opt,name=matrices,proto3" json:"matrices,omitempty"`                       // [stage1][grid] -> 16x16 decorrelation matrix
	MinSpacing     *F2                    `protobuf:"bytes,4,opt,name=min_spacing,json=minSpacing,proto3" json:"min_spacing,omitempty"` // [stage1] -> 17 stabilize spacings
	Grid16W        *F2                    `protobuf:"bytes,5,opt,name=grid16_w,json=grid16W,proto3" json:"grid16_w,omitempty"`
	Grid16Alpha    []float32              `protobuf:"fixed32,6,rep,packed,name=grid16_alpha,json=grid16Alpha,proto3" json:"grid16_alpha,omitempty"`
	Grid16Matrices *F3                    `protobuf:"bytes,7,opt,name=grid16_matrices,json=grid16Matrices,proto3" json:"grid16_matrices,omitempty"` // [sig][config] -> 256-entry flat matrix
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SmplSynthTables) Reset() {
	*x = SmplSynthTables{}
	mi := &file_tables_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmplSynthTables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmplSynthTables) ProtoMessage() {}

func (x *SmplSynthTables) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmplSynthTables.ProtoReflect.Descriptor instead.
func (*SmplSynthTables) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{18}
}

func (x *SmplSynthTables) GetValtables() *F5 {
	if x != nil {
		return x.Valtables
	}
	return nil
}

func (x *SmplSynthTables) GetCentroids() *F3 {
	if x != nil {
		return x.Centroids
	}
	return nil
}

func (x *SmplSynthTables) GetMatrices() *F4 {
	if x != nil {
		return x.Matrices
	}
	return nil
}

func (x *SmplSynthTables) GetMinSpacing() *F2 {
	if x != nil {
		return x.MinSpacing
	}
	return nil
}

func (x *SmplSynthTables) GetGrid16W() *F2 {
	if x != nil {
		return x.Grid16W
	}
	return nil
}

func (x *SmplSynthTables) GetGrid16Alpha() []float32 {
	if x != nil {
		return x.Grid16Alpha
	}
	return nil
}

func (x *SmplSynthTables) GetGrid16Matrices() *F3 {
	if x != nil {
		return x.Grid16Matrices
	}
	return nil
}

// MLow LSF quantizer codebook (the runtime lsf_cb_dump, encoder). Stored zlib+protobuf.
type LsfCb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	St1           []*LsfCbSt1            `protobuf:"bytes,1,rep,name=st1,proto3" json:"st1,omitempty"`                                          // [2]
	St2           []*LsfCbSt2L1          `protobuf:"bytes,2,rep,name=st2,proto3" json:"st2,omitempty"`                                          // [2][2][17]
	MinQi         *I4                    `protobuf:"bytes,3,opt,name=min_qi,json=minQi,proto3" json:"min_qi,omitempty"`                         // [2][2][17][16]
	MaxQi         *I4                    `protobuf:"bytes,4,opt,name=max_qi,json=maxQi,proto3" json:"max_qi,omitempty"`                         // [2][2][17][16]
	Qstep         *F2                    `protobuf:"bytes,5,opt,name=qstep,proto3" json:"qstep,omitempty"`                                      // [2][2]
	MeanV         []float32              `protobuf:"fixed32,6,rep,packed,name=mean_v,json=meanV,proto3" json:"mean_v,omitempty"`                // [16]
	MeanUv        []float32              `protobuf:"fixed32,7,rep,packed,name=mean_uv,json=meanUv,proto3" json:"mean_uv,omitempty"`             // [16]
	RegCond       []float32              `protobuf:"fixed32,8,rep,packed,name=reg_cond,json=regCond,proto3" json:"reg_cond,omitempty"`          // [2]
	MinDistV      []float32              `protobuf:"fixed32,9,rep,packed,name=min_dist_v,json=minDistV,proto3" json:"min_dist_v,omitempty"`     // [17]
	MinDistUv     []float32              `protobuf:"fixed32,10,rep,packed,name=min_dist_uv,json=minDistUv,proto3" json:"min_dist_uv,omitempty"` // [17]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsfCb) Reset() {
	*x = LsfCb{}
	mi := &file_tables_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsfCb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsfCb) ProtoMessage() {}

func (x *LsfCb) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsfCb.ProtoReflect.Descriptor instead.
func (*LsfCb) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{19}
}

func (x *LsfCb) GetSt1() []*LsfCbSt1 {
	if x != nil {
		return x.St1
	}
	return nil
}

func (x *LsfCb) GetSt2() []*LsfCbSt2L1 {
	if x != nil {
		return x.St2
	}
	return nil
}

func (x *LsfCb) GetMinQi() *I4 {
	if x != nil {
		return x.MinQi
	}
	return nil
}

func (x *LsfCb) GetMaxQi() *I4 {
	if x != nil {
		return x.MaxQi
	}
	return nil
}

func (x *LsfCb) GetQstep() *F2 {
	if x != nil {
		return x.Qstep
	}
	return nil
}

func (x *LsfCb) GetMeanV() []float32 {
	if x != nil {
		return x.MeanV
	}
	return nil
}

func (x *LsfCb) GetMeanUv() []float32 {
	if x != nil {
		return x.MeanUv
	}
	return nil
}

func (x *LsfCb) GetRegCond() []float32 {
	if x != nil {
		return x.RegCond
	}
	return nil
}

func (x *LsfCb) GetMinDistV() []float32 {
	if x != nil {
		return x.MinDistV
	}
	return nil
}

func (x *LsfCb) GetMinDistUv() []float32 {
	if x != nil {
		return x.MinDistUv
	}
	return nil
}

type LsfCbSt1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cbhalf        *F2                    `protobuf:"bytes,1,opt,name=cbhalf,proto3" json:"cbhalf,omitempty"`                              // [16][16]
	CInv          *F2                    `protobuf:"bytes,2,opt,name=c_inv,json=cInv,proto3" json:"c_inv,omitempty"`                      // [16][16]
	BitsCond      []float32              `protobuf:"fixed32,3,rep,packed,name=bits_cond,json=bitsCond,proto3" json:"bits_cond,omitempty"` // [17]
	Rotcond       *F3                    `protobuf:"bytes,4,opt,name=rotcond,proto3" json:"rotcond,omitempty"`                            // [2][16][16]
	CbCinv        *F2                    `protobuf:"bytes,5,opt,name=cb_cinv,json=cbCinv,proto3" json:"cb_cinv,omitempty"`                // [16][16]
	We            *F3                    `protobuf:"bytes,6,opt,name=we,proto3" json:"we,omitempty"`                                      // [16][16][16]
	Bits          []float32              `protobuf:"fixed32,7,rep,packed,name=bits,proto3" json:"bits,omitempty"`                         // [16]
	Wie           *F3                    `protobuf:"bytes,8,opt,name=wie,proto3" json:"wie,omitempty"`                                    // [16][16][16]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsfCbSt1) Reset() {
	*x = LsfCbSt1{}
	mi := &file_tables_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsfCbSt1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsfCbSt1) ProtoMessage() {}

func (x *LsfCbSt1) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsfCbSt1.ProtoReflect.Descriptor instead.
func (*LsfCbSt1) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{20}
}

func (x *LsfCbSt1) GetCbhalf() *F2 {
	if x != nil {
		return x.Cbhalf
	}
	return nil
}

func (x *LsfCbSt1) GetCInv() *F2 {
	if x != nil {
		return x.CInv
	}
	return nil
}

func (x *LsfCbSt1) GetBitsCond() []float32 {
	if x != nil {
		return x.BitsCond
	}
	return nil
}

func (x *LsfCbSt1) GetRotcond() *F3 {
	if x != nil {
		return x.Rotcond
	}
	return nil
}

func (x *LsfCbSt1) GetCbCinv() *F2 {
	if x != nil {
		return x.CbCinv
	}
	return nil
}

func (x *LsfCbSt1) GetWe() *F3 {
	if x != nil {
		return x.We
	}
	return nil
}

func (x *LsfCbSt1) GetBits() []float32 {
	if x != nil {
		return x.Bits
	}
	return nil
}

func (x *LsfCbSt1) GetWie() *F3 {
	if x != nil {
		return x.Wie
	}
	return nil
}

type LsfCbSt2L1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D             []*LsfCbSt2L2          `protobuf:"bytes,1,rep,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsfCbSt2L1) Reset() {
	*x = LsfCbSt2L1{}
	mi := &file_tables_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsfCbSt2L1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsfCbSt2L1) ProtoMessage() {}

func (x *LsfCbSt2L1) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsfCbSt2L1.ProtoReflect.Descriptor instead.
func (*LsfCbSt2L1) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{21}
}

func (x *LsfCbSt2L1) GetD() []*LsfCbSt2L2 {
	if x != nil {
		return x.D
	}
	return nil
}

type LsfCbSt2L2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D             []*LsfCbSt2            `protobuf:"bytes,1,rep,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsfCbSt2L2) Reset() {
	*x = LsfCbSt2L2{}
	mi := &file_tables_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsfCbSt2L2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsfCbSt2L2) ProtoMessage() {}

func (x *LsfCbSt2L2) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsfCbSt2L2.ProtoReflect.Descriptor instead.
func (*LsfCbSt2L2) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{22}
}

func (x *LsfCbSt2L2) GetD() []*LsfCbSt2 {
	if x != nil {
		return x.D
	}
	return nil
}

type LsfCbSt2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumQlvls      []int32                `protobuf:"varint,1,rep,packed,name=num_qlvls,json=numQlvls,proto3" json:"num_qlvls,omitempty"` // [16]
	Qlvls         *F2                    `protobuf:"bytes,2,opt,name=qlvls,proto3" json:"qlvls,omitempty"`                               // [16][n]
	NumBits       *F2                    `protobuf:"bytes,3,opt,name=num_bits,json=numBits,proto3" json:"num_bits,omitempty"`            // [16][n]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsfCbSt2) Reset() {
	*x = LsfCbSt2{}
	mi := &file_tables_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsfCbSt2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsfCbSt2) ProtoMessage() {}

func (x *LsfCbSt2) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsfCbSt2.ProtoReflect.Descriptor instead.
func (*LsfCbSt2) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{23}
}

func (x *LsfCbSt2) GetNumQlvls() []int32 {
	if x != nil {
		return x.NumQlvls
	}
	return nil
}

func (x *LsfCbSt2) GetQlvls() *F2 {
	if x != nil {
		return x.Qlvls
	}
	return nil
}

func (x *LsfCbSt2) GetNumBits() *F2 {
	if x != nil {
		return x.NumBits
	}
	return nil
}

var File_tables_proto protoreflect.FileDescriptor

var file_tables_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x0a,
	0x48, 0x65, 0x61, 0x70, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x12, 0x2d, 0x0a, 0x07, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x6c,
	0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x52, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x11, 0x0a, 0x04, 0x67, 0x5f, 0x63,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x67, 0x43, 0x63, 0x12, 0x13, 0x0a, 0x05,
	0x67, 0x5f, 0x6e, 0x72, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x67, 0x4e, 0x72,
	0x67, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x5f, 0x70, 0x69, 0x74, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x67, 0x50, 0x69, 0x74, 0x63, 0x68, 0x12, 0x13, 0x0a, 0x05, 0x67, 0x5f,
	0x63, 0x6c, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x67, 0x43, 0x6c, 0x6b, 0x22,
	0x30, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0xc1, 0x01, 0x0a, 0x0d, 0x53, 0x6d, 0x70, 0x6c, 0x4c, 0x73, 0x66, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x07, 0x6c, 0x73, 0x66, 0x5f, 0x73, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x2e, 0x43, 0x64, 0x66, 0x52, 0x06, 0x6c, 0x73, 0x66, 0x53, 0x65, 0x6c, 0x12, 0x2f,
	0x0a, 0x08, 0x6c, 0x73, 0x66, 0x5f, 0x67, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x4c,
	0x73, 0x66, 0x47, 0x72, 0x69, 0x64, 0x52, 0x07, 0x6c, 0x73, 0x66, 0x47, 0x72, 0x69, 0x64, 0x12,
	0x37, 0x0a, 0x0a, 0x6c, 0x73, 0x66, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x32, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x73, 0x2e, 0x4c, 0x73, 0x66, 0x53, 0x74, 0x61, 0x67, 0x65, 0x32, 0x53, 0x31, 0x52, 0x09, 0x6c,
	0x73, 0x66, 0x53, 0x74, 0x61, 0x67, 0x65, 0x32, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x73, 0x66, 0x5f,
	0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x6c, 0x73, 0x66,
	0x45, 0x78, 0x74, 0x72, 0x61, 0x22, 0x13, 0x0a, 0x03, 0x43, 0x64, 0x66, 0x12, 0x0c, 0x0a, 0x01,
	0x76, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x01, 0x76, 0x22, 0x77, 0x0a, 0x07, 0x4c, 0x73,
	0x66, 0x47, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x31, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x31, 0x12, 0x1d, 0x0a,
	0x0a, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x31, 0x5f, 0x61, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x31, 0x41, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x30, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x30, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x30, 0x5f, 0x61,
	0x6c, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x30,
	0x41, 0x6c, 0x74, 0x22, 0x3f, 0x0a, 0x0b, 0x4c, 0x73, 0x66, 0x53, 0x74, 0x61, 0x67, 0x65, 0x32,
	0x53, 0x31, 0x12, 0x30, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73,
	0x2e, 0x4c, 0x73, 0x66, 0x53, 0x74, 0x61, 0x67, 0x65, 0x32, 0x53, 0x32, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x22, 0x3b, 0x0a, 0x0b, 0x4c, 0x73, 0x66, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x32, 0x53, 0x32, 0x12, 0x2c, 0x0a, 0x04, 0x67, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e,
	0x4c, 0x73, 0x66, 0x53, 0x74, 0x61, 0x67, 0x65, 0x32, 0x53, 0x33, 0x52, 0x04, 0x67, 0x72, 0x69,
	0x64, 0x22, 0x35, 0x0a, 0x0b, 0x4c, 0x73, 0x66, 0x53, 0x74, 0x61, 0x67, 0x65, 0x32, 0x53, 0x33,
	0x12, 0x26, 0x0a, 0x05, 0x63, 0x6f, 0x65, 0x66, 0x66, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x43, 0x64,
	0x66, 0x52, 0x05, 0x63, 0x6f, 0x65, 0x66, 0x66, 0x22, 0x12, 0x0a, 0x02, 0x46, 0x31, 0x12, 0x0c,
	0x0a, 0x01, 0x76, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x01, 0x76, 0x22, 0x23, 0x0a, 0x02,
	0x46, 0x32, 0x12, 0x1d, 0x0a, 0x01, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x31, 0x52, 0x01,
	0x64, 0x22, 0x23, 0x0a, 0x02, 0x46, 0x33, 0x12, 0x1d, 0x0a, 0x01, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73,
	0x2e, 0x46, 0x32, 0x52, 0x01, 0x64, 0x22, 0x23, 0x0a, 0x02, 0x46, 0x34, 0x12, 0x1d, 0x0a, 0x01,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x33, 0x52, 0x01, 0x64, 0x22, 0x23, 0x0a, 0x02, 0x46,
	0x35, 0x12, 0x1d, 0x0a, 0x01, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d,
	0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x34, 0x52, 0x01, 0x64,
	0x22, 0x12, 0x0a, 0x02, 0x55, 0x31, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x01, 0x76, 0x22, 0x12, 0x0a, 0x02, 0x49, 0x31, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x01, 0x76, 0x22, 0x23, 0x0a, 0x02, 0x49, 0x32, 0x12, 0x1d,
	0x0a, 0x01, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6c, 0x6f, 0x77,
	0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x49, 0x31, 0x52, 0x01, 0x64, 0x22, 0x23, 0x0a,
	0x02, 0x49, 0x33, 0x12, 0x1d, 0x0a, 0x01, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x49, 0x32, 0x52,
	0x01, 0x64, 0x22, 0x23, 0x0a, 0x02, 0x49, 0x34, 0x12, 0x1d, 0x0a, 0x01, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x73, 0x2e, 0x49, 0x33, 0x52, 0x01, 0x64, 0x22, 0xd7, 0x02, 0x0a, 0x0f, 0x53, 0x6d, 0x70, 0x6c,
	0x53, 0x79, 0x6e, 0x74, 0x68, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x76,
	0x61, 0x6c, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x35, 0x52,
	0x09, 0x76, 0x61, 0x6c, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x63, 0x65,
	0x6e, 0x74, 0x72, 0x6f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x33, 0x52, 0x09,
	0x63, 0x65, 0x6e, 0x74, 0x72, 0x6f, 0x69, 0x64, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x6d, 0x61, 0x74,
	0x72, 0x69, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6c,
	0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x34, 0x52, 0x08, 0x6d, 0x61,
	0x74, 0x72, 0x69, 0x63, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x70,
	0x61, 0x63, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6c,
	0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x32, 0x52, 0x0a, 0x6d, 0x69,
	0x6e, 0x53, 0x70, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x12, 0x2a, 0x0a, 0x08, 0x67, 0x72, 0x69, 0x64,
	0x31, 0x36, 0x5f, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6c, 0x6f,
	0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x32, 0x52, 0x07, 0x67, 0x72, 0x69,
	0x64, 0x31, 0x36, 0x57, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x72, 0x69, 0x64, 0x31, 0x36, 0x5f, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x18, 0x06, 0x20, 0x03, 0x28, 0x02, 0x52, 0x0b, 0x67, 0x72, 0x69, 0x64,
	0x31, 0x36, 0x41, 0x6c, 0x70, 0x68, 0x61, 0x12, 0x38, 0x0a, 0x0f, 0x67, 0x72, 0x69, 0x64, 0x31,
	0x36, 0x5f, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x63, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x46,
	0x33, 0x52, 0x0e, 0x67, 0x72, 0x69, 0x64, 0x31, 0x36, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x63, 0x65,
	0x73, 0x22, 0xdb, 0x02, 0x0a, 0x05, 0x4c, 0x73, 0x66, 0x43, 0x62, 0x12, 0x27, 0x0a, 0x03, 0x73,
	0x74, 0x31, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x4c, 0x73, 0x66, 0x43, 0x62, 0x53, 0x74, 0x31, 0x52,
	0x03, 0x73, 0x74, 0x31, 0x12, 0x29, 0x0a, 0x03, 0x73, 0x74, 0x32, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e,
	0x4c, 0x73, 0x66, 0x43, 0x62, 0x53, 0x74, 0x32, 0x4c, 0x31, 0x52, 0x03, 0x73, 0x74, 0x32, 0x12,
	0x26, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x5f, 0x71, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x49, 0x34,
	0x52, 0x05, 0x6d, 0x69, 0x6e, 0x51, 0x69, 0x12, 0x26, 0x0a, 0x06, 0x6d, 0x61, 0x78, 0x5f, 0x71,
	0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x49, 0x34, 0x52, 0x05, 0x6d, 0x61, 0x78, 0x51, 0x69, 0x12,
	0x25, 0x0a, 0x05, 0x71, 0x73, 0x74, 0x65, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x32, 0x52,
	0x05, 0x71, 0x73, 0x74, 0x65, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x65, 0x61, 0x6e, 0x5f, 0x76,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x02, 0x52, 0x05, 0x6d, 0x65, 0x61, 0x6e, 0x56, 0x12, 0x17, 0x0a,
	0x07, 0x6d, 0x65, 0x61, 0x6e, 0x5f, 0x75, 0x76, 0x18, 0x07, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06,
	0x6d, 0x65, 0x61, 0x6e, 0x55, 0x76, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x5f, 0x63, 0x6f,
	0x6e, 0x64, 0x18, 0x08, 0x20, 0x03, 0x28, 0x02, 0x52, 0x07, 0x72, 0x65, 0x67, 0x43, 0x6f, 0x6e,
	0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x5f, 0x76, 0x18,
	0x09, 0x20, 0x03, 0x28, 0x02, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x44, 0x69, 0x73, 0x74, 0x56, 0x12,
	0x1e, 0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x5f, 0x75, 0x76, 0x18, 0x0a,
	0x20, 0x03, 0x28, 0x02, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x44, 0x69, 0x73, 0x74, 0x55, 0x76, 0x22,
	0xa3, 0x02, 0x0a, 0x08, 0x4c, 0x73, 0x66, 0x43, 0x62, 0x53, 0x74, 0x31, 0x12, 0x27, 0x0a, 0x06,
	0x63, 0x62, 0x68, 0x61, 0x6c, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d,
	0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x32, 0x52, 0x06, 0x63,
	0x62, 0x68, 0x61, 0x6c, 0x66, 0x12, 0x24, 0x0a, 0x05, 0x63, 0x5f, 0x69, 0x6e, 0x76, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x2e, 0x46, 0x32, 0x52, 0x04, 0x63, 0x49, 0x6e, 0x76, 0x12, 0x1b, 0x0a, 0x09, 0x62,
	0x69, 0x74, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x02, 0x52, 0x08,
	0x62, 0x69, 0x74, 0x73, 0x43, 0x6f, 0x6e, 0x64, 0x12, 0x29, 0x0a, 0x07, 0x72, 0x6f, 0x74, 0x63,
	0x6f, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6c, 0x6f, 0x77,
	0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x33, 0x52, 0x07, 0x72, 0x6f, 0x74, 0x63,
	0x6f, 0x6e, 0x64, 0x12, 0x28, 0x0a, 0x07, 0x63, 0x62, 0x5f, 0x63, 0x69, 0x6e, 0x76, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x2e, 0x46, 0x32, 0x52, 0x06, 0x63, 0x62, 0x43, 0x69, 0x6e, 0x76, 0x12, 0x1f, 0x0a,
	0x02, 0x77, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6c, 0x6f, 0x77,
	0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x33, 0x52, 0x02, 0x77, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x62, 0x69, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x02, 0x52, 0x04, 0x62, 0x69,
	0x74, 0x73, 0x12, 0x21, 0x0a, 0x03, 0x77, 0x69, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x33,
	0x52, 0x03, 0x77, 0x69, 0x65, 0x22, 0x33, 0x0a, 0x0a, 0x4c, 0x73, 0x66, 0x43, 0x62, 0x53, 0x74,
	0x32, 0x4c, 0x31, 0x12, 0x25, 0x0a, 0x01, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x4c, 0x73, 0x66,
	0x43, 0x62, 0x53, 0x74, 0x32, 0x4c, 0x32, 0x52, 0x01, 0x64, 0x22, 0x31, 0x0a, 0x0a, 0x4c, 0x73,
	0x66, 0x43, 0x62, 0x53, 0x74, 0x32, 0x4c, 0x32, 0x12, 0x23, 0x0a, 0x01, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x73, 0x2e, 0x4c, 0x73, 0x66, 0x43, 0x62, 0x53, 0x74, 0x32, 0x52, 0x01, 0x64, 0x22, 0x7a, 0x0a,
	0x08, 0x4c, 0x73, 0x66, 0x43, 0x62, 0x53, 0x74, 0x32, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x75, 0x6d,
	0x5f, 0x71, 0x6c, 0x76, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x75,
	0x6d, 0x51, 0x6c, 0x76, 0x6c, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x71, 0x6c, 0x76, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x2e, 0x46, 0x32, 0x52, 0x05, 0x71, 0x6c, 0x76, 0x6c, 0x73, 0x12, 0x2a, 0x0a,
	0x08, 0x6e, 0x75, 0x6d, 0x5f, 0x62, 0x69, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x32,
	0x52, 0x07, 0x6e, 0x75, 0x6d, 0x42, 0x69, 0x74, 0x73, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x75, 0x72, 0x70, 0x73, 0x68, 0x65, 0x6c,
	0x6c, 0x2f, 0x6d, 0x65, 0x6f, 0x77, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x6d, 0x6c, 0x6f,
	0x77, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_tables_proto_rawDescOnce sync.Once
	file_tables_proto_rawDescData []byte
)

func file_tables_proto_rawDescGZIP() []byte {
	file_tables_proto_rawDescOnce.Do(func() {
		file_tables_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tables_proto_rawDesc), len(file_tables_proto_rawDesc)))
	})
	return file_tables_proto_rawDescData
}

var file_tables_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_tables_proto_goTypes = []any{
	(*HeapWindow)(nil),      // 0: mlow.tables.HeapWindow
	(*Region)(nil),          // 1: mlow.tables.Region
	(*SmplLsfTables)(nil),   // 2: mlow.tables.SmplLsfTables
	(*Cdf)(nil),             // 3: mlow.tables.Cdf
	(*LsfGrid)(nil),         // 4: mlow.tables.LsfGrid
	(*LsfStage2S1)(nil),     // 5: mlow.tables.LsfStage2S1
	(*LsfStage2S2)(nil),     // 6: mlow.tables.LsfStage2S2
	(*LsfStage2S3)(nil),     // 7: mlow.tables.LsfStage2S3
	(*F1)(nil),              // 8: mlow.tables.F1
	(*F2)(nil),              // 9: mlow.tables.F2
	(*F3)(nil),              // 10: mlow.tables.F3
	(*F4)(nil),              // 11: mlow.tables.F4
	(*F5)(nil),              // 12: mlow.tables.F5
	(*U1)(nil),              // 13: mlow.tables.U1
	(*I1)(nil),              // 14: mlow.tables.I1
	(*I2)(nil),              // 15: mlow.tables.I2
	(*I3)(nil),              // 16: mlow.tables.I3
	(*I4)(nil),              // 17: mlow.tables.I4
	(*SmplSynthTables)(nil), // 18: mlow.tables.SmplSynthTables
	(*LsfCb)(nil),           // 19: mlow.tables.LsfCb
	(*LsfCbSt1)(nil),        // 20: mlow.tables.LsfCbSt1
	(*LsfCbSt2L1)(nil),      // 21: mlow.tables.LsfCbSt2L1
	(*LsfCbSt2L2)(nil),      // 22: mlow.tables.LsfCbSt2L2
	(*LsfCbSt2)(nil),        // 23: mlow.tables.LsfCbSt2
}
var file_tables_proto_depIdxs = []int32{
	1,  // 0: mlow.tables.HeapWindow.regions:type_name -> mlow.tables.Region
	3,  // 1: mlow.tables.SmplLsfTables.lsf_sel:type_name -> mlow.tables.Cdf
	4,  // 2: mlow.tables.SmplLsfTables.lsf_grid:type_name -> mlow.tables.LsfGrid
	5,  // 3: mlow.tables.SmplLsfTables.lsf_stage2:type_name -> mlow.tables.LsfStage2S1
	6,  // 4: mlow.tables.LsfStage2S1.config:type_name -> mlow.tables.LsfStage2S2
	7,  // 5: mlow.tables.LsfStage2S2.grid:type_name -> mlow.tables.LsfStage2S3
	3,  // 6: mlow.tables.LsfStage2S3.coeff:type_name -> mlow.tables.Cdf
	8,  // 7: mlow.tables.F2.d:type_name -> mlow.tables.F1
	9,  // 8: mlow.tables.F3.d:type_name -> mlow.tables.F2
	10, // 9: mlow.tables.F4.d:type_name -> mlow.tables.F3
	11, // 10: mlow.tables.F5.d:type_name -> mlow.tables.F4
	14, // 11: mlow.tables.I2.d:type_name -> mlow.tables.I1
	15, // 12: mlow.tables.I3.d:type_name -> mlow.tables.I2
	16, // 13: mlow.tables.I4.d:type_name -> mlow.tables.I3
	12, // 14: mlow.tables.SmplSynthTables.valtables:type_name -> mlow.tables.F5
	10, // 15: mlow.tables.SmplSynthTables.centroids:type_name -> mlow.tables.F3
	11, // 16: mlow.tables.SmplSynthTables.matrices:type_name -> mlow.tables.F4
	9,  // 17: mlow.tables.SmplSynthTables.min_spacing:type_name -> mlow.tables.F2
	9,  // 18: mlow.tables.SmplSynthTables.grid16_w:type_name -> mlow.tables.F2
	10, // 19: mlow.tables.SmplSynthTables.grid16_matrices:type_name -> mlow.tables.F3
	20, // 20: mlow.tables.LsfCb.st1:type_name -> mlow.tables.LsfCbSt1
	21, // 21: mlow.tables.LsfCb.st2:type_name -> mlow.tables.LsfCbSt2L1
	17, // 22: mlow.tables.LsfCb.min_qi:type_name -> mlow.tables.I4
	17, // 23: mlow.tables.LsfCb.max_qi:type_name -> mlow.tables.I4
	9,  // 24: mlow.tables.LsfCb.qstep:type_name -> mlow.tables.F2
	9,  // 25: mlow.tables.LsfCbSt1.cbhalf:type_name -> mlow.tables.F2
	9,  // 26: mlow.tables.LsfCbSt1.c_inv:type_name -> mlow.tables.F2
	10, // 27: mlow.tables.LsfCbSt1.rotcond:type_name -> mlow.tables.F3
	9,  // 28: mlow.tables.LsfCbSt1.cb_cinv:type_name -> mlow.tables.F2
	10, // 29: mlow.tables.LsfCbSt1.we:type_name -> mlow.tables.F3
	10, // 30: mlow.tables.LsfCbSt1.wie:type_name -> mlow.tables.F3
	22, // 31: mlow.tables.LsfCbSt2L1.d:type_name -> mlow.tables.LsfCbSt2L2
	23, // 32: mlow.tables.LsfCbSt2L2.d:type_name -> mlow.tables.LsfCbSt2
	9,  // 33: mlow.tables.LsfCbSt2.qlvls:type_name -> mlow.tables.F2
	9,  // 34: mlow.tables.LsfCbSt2.num_bits:type_name -> mlow.tables.F2
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_tables_proto_init() }
func file_tables_proto_init() {
	if File_tables_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tables_proto_rawDesc), len(file_tables_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tables_proto_goTypes,
		DependencyIndexes: file_tables_proto_depIdxs,
		MessageInfos:      file_tables_proto_msgTypes,
	}.Build()
	File_tables_proto = out.File
	file_tables_proto_goTypes = nil
	file_tables_proto_depIdxs = nil
}
