package api

import (
	legacy "github.com/nocodeleaks/quepasa/api/legacy"
)

func legacyHandlers() legacy.Handlers {
	return legacy.Handlers{
		"BasicHealthController":             BasicHealthController,
		"HealthController":                  HealthController,
		"EnvironmentController":             EnvironmentController,
		"LoginConfigController":             LoginConfigController,
		"AccountController":                 AccountController,
		"CreateInformationController":       CreateInformationController,
		"GetInformationController":          GetInformationController,
		"UpdateInformationController":       UpdateInformationController,
		"DeleteInformationController":       DeleteInformationController,
		"ScannerController":                 ScannerController,
		"PairCodeController":                PairCodeController,
		"CommandController":                 CommandController,
		"GetMessageController":              GetMessageController,
		"RevokeController":                  RevokeController,
		"MarkReadController":                MarkReadController,
		"SendAny":                           SendAny,
		"SendDocument":                      SendDocument,
		"SendDocumentFromBinary":            SendDocumentFromBinary,
		"ReceiveAPIHandler":                 ReceiveAPIHandler,
		"RedispatchAPIHandler":              RedispatchAPIHandler,
		"DownloadController":                DownloadController,
		"PictureController":                 PictureController,
		"WebhookController":                 WebhookController,
		"RabbitMQController":                RabbitMQController,
		"InviteController":                  InviteController,
		"ContactsController":                ContactsController,
		"ContactSearchController":           ContactSearchController,
		"IsOnWhatsappController":            IsOnWhatsappController,
		"GetUserIdentifierController":       GetUserIdentifierController,
		"GetPhoneController":                GetPhoneController,
		"UserInfoController":                UserInfoController,
		"Spam":                              Spam,
		"FetchAllGroupsController":          FetchAllGroupsController,
		"GetGroupController":                GetGroupController,
		"CreateGroupController":             CreateGroupController,
		"LeaveGroupController":              LeaveGroupController,
		"SetGroupNameController":            SetGroupNameController,
		"SetGroupTopicController":           SetGroupTopicController,
		"SetGroupPhotoController":           SetGroupPhotoController,
		"UpdateGroupParticipantsController": UpdateGroupParticipantsController,
		"GroupMembershipRequestsController": GroupMembershipRequestsController,
		"ChatPresenceController":            ChatPresenceController,
		"ConversationLabelController":       ConversationLabelController,
		"ConversationChatLabelController":   ConversationChatLabelController,
		"MarkChatAsReadController":          MarkChatAsReadController,
		"MarkChatAsUnreadController":        MarkChatAsUnreadController,
		"ArchiveChatController":             ArchiveChatController,
		"EditMessageController":             EditMessageController,
		"RestoreDiagnoseController":         RestoreDiagnoseController,
		"RestoreAutoController":             RestoreAutoController,
		"RestoreManualController":           RestoreManualController,
		"InformationControllerV3":           InformationControllerV3,
	}
}
